/**
 * Human-readable names for each check ID.
 * Covers both the new service-based policy structure
 * (iam_XX, ec2_XX, s3_XX, …) and the legacy CHECK_XX IDs.
 * Used across violations, policies, remediation, and
 * executive summary pages.
 */
const CHECK_NAMES: Record<string, string> = {
  // ── IAM (identity) ─────────────────────────────────────────
  iam_01: "Root Account MFA Not Enabled",
  iam_02: "Password Policy Minimum Length < 14",
  iam_03: "Password Policy: No Uppercase Required",
  iam_04: "Password Policy: No Lowercase Required",
  iam_05: "Password Policy: No Numbers Required",
  iam_06: "Password Policy: No Symbols Required",
  iam_07: "Password Policy: Insufficient Reuse Prevention",
  iam_08: "Password Policy: Max Age Exceeds 90 Days",
  iam_09: "IAM User MFA Not Enabled",
  iam_10: "Root Account Has Active Access Keys",
  iam_11: "IAM User Has Inline Policies",
  iam_12: "IAM User Has AdministratorAccess",
  iam_13: "Access Key Not Rotated Within 90 Days",
  iam_14: "Inactive IAM User With Active Credentials",
  iam_15: "IAM Access Analyzer Not Enabled",
  iam_16: "IAM Policy Allows Action:* on Resource:*",
  iam_17: "Unused Access Key Active > 90 Days",
  iam_18: "IAM Role Trust Policy Allows All Principals",
  iam_19: "IAM User Has Both Console and API Access",
  iam_20: "No IAM Support Role Found",

  // ── Cognito (identity) ─────────────────────────────────────
  cognito_01: "Cognito User Pool MFA Disabled",
  cognito_02: "Cognito Password Too Short (< 8)",
  cognito_03: "Cognito: No Uppercase Required",
  cognito_04: "Cognito: No Lowercase Required",
  cognito_05: "Cognito: No Numbers Required",
  cognito_06: "Cognito: No Symbols Required",
  cognito_07: "Cognito Advanced Security Not Enforced",
  cognito_08: "Cognito Temp Password Validity > 7 Days",
  cognito_09: "Cognito No Auto-Verified Attributes",
  cognito_10: "Cognito No New Device Challenge",
  cognito_11: "Cognito Access Token Valid > 60 Min",
  cognito_12: "Cognito Refresh Token Valid > 30 Days",
  cognito_13: "Cognito Identity Pool Allows Unauthenticated",
  cognito_14: "Cognito App Client Uses Plain Password Auth",
  cognito_15: "Cognito Server Client Missing Secret",
  cognito_16: "Cognito User Pool Deletion Protection Off",
  cognito_17: "Cognito Using Default Email Sender",

  // ── EC2 (compute) ──────────────────────────────────────────
  ec2_01: "EC2 IMDSv2 Not Enforced",
  ec2_02: "Production EC2 Has Public IP",
  ec2_03: "EC2 Running in Default VPC",
  ec2_04: "EC2 Detailed Monitoring Disabled",
  ec2_05: "Security Group Allows SSH from 0.0.0.0/0",
  ec2_06: "Security Group Allows RDP from 0.0.0.0/0",
  ec2_07: "Security Group Allows All Inbound Traffic",
  ec2_08: "EC2 Root EBS Volume Not Encrypted",
  ec2_09: "EC2 Instance Has Admin IAM Role",
  ec2_10: "EBS Snapshot Publicly Accessible",
  ec2_11: "Production EC2 Termination Protection Off",
  ec2_12: "EC2 Instance Stopped > 90 Days",
  ec2_13: "Security Group Allows All IPv6 Inbound",
  ec2_14: "EC2 Instance Has No IAM Instance Profile",
  ec2_15: "Internal Security Group Allows HTTPS Public",
  ec2_16: "Production Security Group Allows All Outbound",
  ec2_17: "Production EC2 Uses Key Pair Instead of SSM",
  ec2_18: "EC2 Using Deprecated Instance Type",
  ec2_19: "Unused Elastic IP Not Released",
  ec2_20: "Account-Owned AMI Publicly Shared",

  // ── Serverless / Containers (compute) ─────────────────────
  serverless_01: "Lambda X-Ray Tracing Not Enabled",
  serverless_02: "Lambda Env Variables Not KMS Encrypted",
  serverless_03: "Lambda Using Deprecated Runtime",
  serverless_04: "Lambda Resource Policy Allows Public Invocation",
  serverless_05: "Lambda Execution Role Has AdministratorAccess",
  serverless_06: "ECS Container Running in Privileged Mode",
  serverless_07: "ECS Container Root Filesystem Not Read-Only",
  serverless_08: "ECS Container Not Using CloudWatch Logs",
  serverless_09: "ECS Task Using Host Network Mode",
  serverless_10: "ECS Cluster Container Insights Disabled",
  serverless_11: "EKS API Endpoint Publicly Accessible",
  serverless_12: "EKS Secrets Encryption Not Enabled",
  serverless_13: "EKS Audit Logs Not Enabled",
  serverless_14: "EKS Node Group Not in Private Subnet",
  serverless_15: "EKS Using End-of-Life Kubernetes Version",
  serverless_16: "ECR Image Scanning Disabled",
  serverless_17: "ECR Repository Publicly Accessible",
  serverless_18: "ECR Image Tag Immutability Disabled",
  serverless_19: "ECR No Lifecycle Policy Configured",
  serverless_20: "ECR Repository Not Encrypted with KMS",

  // ── VPC (network) ──────────────────────────────────────────
  vpc_01: "VPC Flow Logs Not Enabled",
  vpc_02: "Default VPC Has Resources Attached",
  vpc_03: "Default Security Group Allows Inbound",
  vpc_04: "Default Security Group Allows Outbound",
  vpc_05: "NACL Allows All Inbound from 0.0.0.0/0",
  vpc_06: "VPC DNS Resolution Disabled",
  vpc_07: "VPC DNS Hostnames Disabled",
  vpc_08: "Private Subnet Auto-Assigns Public IPs",
  vpc_09: "Private Route Table Routes to Internet Gateway",
  vpc_10: "Production VPC Spans Only 1 AZ",
  vpc_11: "Security Group Allows All Ports from Internet",
  vpc_12: "VPC Peering Connection Uses Unrestricted CIDR",
  vpc_13: "Production VPC Has No S3 VPC Endpoint",
  vpc_14: "VPC CIDR Block Too Broad (/8)",
  vpc_15: "NACL Allows Admin Ports from Internet",
  vpc_16: "Transit Gateway Default Route Propagation On",
  vpc_17: "Production VPC Has No NAT Gateway",
  vpc_18: "Security Group Allows Database Ports from Internet",
  vpc_19: "Restricted VPC Has Internet Gateway",
  vpc_20: "VPC Flow Logs Capture ACCEPT Traffic Only",

  // ── WAF (network) ──────────────────────────────────────────
  waf_01: "WAF Not Associated with CloudFront",
  waf_02: "WAF Not Associated with ALB",
  waf_03: "AWS Managed WAF Rules Not Enabled",
  waf_04: "WAF Rate-Based Rules Not Configured",
  waf_05: "WAF SQL Injection Protection Disabled",
  waf_06: "WAF XSS Protection Disabled",
  waf_07: "WAF Logging Not Enabled",
  waf_08: "WAF IP Reputation Rules Not Enabled",
  waf_09: "WAF Bot Control Not Enabled",
  waf_10: "WAF Critical Rules in COUNT-Only Mode",
  waf_11: "AWS Shield Advanced Not Enabled",
  waf_12: "WAF API Default Action Not BLOCK",
  waf_13: "WAF Known Bad Inputs Rules Not Enabled",
  waf_14: "WAF Log Redaction Hiding Critical Fields",

  // ── API Gateway / Load Balancer (network) ─────────────────
  apigw_01: "API Gateway Access Logging Not Enabled",
  apigw_02: "API Gateway Execution Logging Not Enabled",
  apigw_03: "API Gateway TLS 1.2 Not Enforced",
  apigw_04: "API Gateway WAF WebACL Not Associated",
  apigw_05: "API Gateway Throttling Not Configured",
  apigw_06: "Private API Not Using VPC Endpoint",
  apigw_07: "API Gateway CORS Allows All Origins",
  apigw_08: "API Gateway Keys Not Required for Usage Plans",
  apigw_09: "API Gateway Request Validation Disabled",
  apigw_10: "API Gateway Backend Certificate Missing",
  apigw_11: "Load Balancer Has No HTTPS Listener",
  apigw_12: "Load Balancer TLS Policy Below TLS 1.2",
  apigw_13: "Load Balancer Access Logging Disabled",
  apigw_14: "Production Load Balancer Deletion Protection Off",
  apigw_15: "Load Balancer HTTP Not Redirecting to HTTPS",
  apigw_16: "Internal Load Balancer Is Internet-Facing",
  apigw_17: "Production ALB Not Associated with WAF",
  apigw_18: "Load Balancer TLS Certificate Expired",
  apigw_19: "Load Balancer Drop Invalid Headers Disabled",
  apigw_20: "Load Balancer Deployed Across Only 1 AZ",

  // ── S3 (data_protection) ───────────────────────────────────
  s3_01: "S3 BlockPublicAcls Not Enabled",
  s3_02: "S3 IgnorePublicAcls Not Enabled",
  s3_03: "S3 BlockPublicPolicy Not Enabled",
  s3_04: "S3 RestrictPublicBuckets Not Enabled",
  s3_05: "S3 Server-Side Encryption Not Enabled",
  s3_06: "Sensitive S3 Bucket Versioning Disabled",
  s3_07: "Sensitive S3 Bucket MFA Delete Disabled",
  s3_08: "Production S3 Bucket Access Logging Disabled",
  s3_09: "S3 Bucket Policy Allows Unencrypted HTTP",
  s3_10: "S3 ACL Grants Public Read Access",
  s3_11: "S3 ACL Grants Public Write Access",
  s3_12: "Production S3 Bucket Has No Lifecycle Policy",
  s3_13: "Compliance S3 Bucket Object Lock Disabled",
  s3_14: "S3 CORS Configuration Allows All Origins",
  s3_15: "Sensitive S3 Bucket Not Using KMS Encryption",
  s3_16: "S3 Policy Allows Principal:* Without Conditions",
  s3_17: "High-Criticality S3 Bucket Has No Replication",
  s3_18: "Security-Monitored S3 Bucket No Event Notifications",
  s3_19: "S3 Cross-Account Access Missing Org ID Condition",
  s3_20: "Large S3 Bucket No Intelligent-Tiering",

  // ── KMS (data_protection) ──────────────────────────────────
  kms_01: "KMS Customer-Managed Key Rotation Not Enabled",
  kms_02: "KMS Key Policy Allows Principal:*",
  kms_03: "KMS Key Pending Deletion Without Approval Tag",
  kms_04: "KMS Key Policy Mixes Admin and User Roles",
  kms_05: "KMS Key Has No Description",
  kms_06: "KMS Multi-Region Key Used Without Justification",
  kms_07: "KMS Key Policy Allows Unknown Cross-Account",
  kms_08: "KMS Key Missing Owner/Purpose Tags",
  kms_09: "Disabled KMS Key Not Scheduled for Deletion",
  kms_10: "KMS Key Policy Grants Root Wildcard Actions",
  kms_11: "KMS Key Alias Uses Reserved aws/ Prefix",
  kms_12: "KMS Key for S3 Rotation Not Enabled",
  kms_13: "No CloudWatch Alarm for KMS Key Deletion",
  kms_14: "KMS Key Material Origin Is EXTERNAL",
  kms_15: "KMS Key Grant Allows Decrypt to Unapproved Service",

  // ── Secrets Manager (data_protection) ─────────────────────
  secretsmanager_01: "Secrets Manager Auto-Rotation Not Enabled",
  secretsmanager_02: "Secret Rotation Interval Exceeds 90 Days",
  secretsmanager_03: "Secret Resource Policy Allows Public Access",
  secretsmanager_04: "Secret Not Encrypted with Customer KMS Key",
  secretsmanager_05: "Secret Unused for More Than 90 Days",
  secretsmanager_06: "Secret Has Cross-Account Access Without Condition",
  secretsmanager_07: "Secret Scheduled for Deletion Without Approval",
  secretsmanager_08: "Secret Missing Owner/Purpose Tags",
  secretsmanager_09: "Secret Name Reveals Its Type or Purpose",
  secretsmanager_10: "Secret Rotation Function Is Orphaned",
  secretsmanager_11: "Secret Has No Description",
  secretsmanager_12: "Critical Secret Has No Multi-Region Replication",
  secretsmanager_13: "Secret Policy Has Wildcard Principal",

  // ── Database — RDS / DynamoDB / Aurora (data_protection) ──
  db_01: "RDS Instance Publicly Accessible",
  db_02: "RDS Storage Not Encrypted",
  db_03: "RDS Backup Retention Period < 7 Days",
  db_04: "Production RDS Instance Not Multi-AZ",
  db_05: "Production RDS Deletion Protection Off",
  db_06: "RDS IAM Database Authentication Not Enabled",
  db_07: "RDS Snapshot Publicly Accessible",
  db_08: "RDS CloudWatch Log Exports Not Enabled",
  db_09: "RDS Auto Minor Version Upgrade Disabled",
  db_10: "RDS Using Default Database Port",
  db_11: "DynamoDB Encryption Not Using KMS",
  db_12: "DynamoDB Point-in-Time Recovery Not Enabled",
  db_13: "Production DynamoDB Deletion Protection Off",
  db_14: "DynamoDB Resource Policy Allows Public Access",
  db_15: "Production DynamoDB Auto-Scaling Not Configured",
  db_16: "Aurora Cluster Publicly Accessible",
  db_17: "Aurora Storage Not Encrypted",
  db_18: "Production Aurora Deletion Protection Off",
  db_19: "Aurora Backtrack Not Enabled for Critical Clusters",
  db_20: "Aurora IAM Authentication Not Enabled",

  // ── Storage — EBS / EFS (data_protection) ─────────────────
  storage_01: "EBS Volume Not Encrypted",
  storage_02: "EBS Default Encryption Not Enabled at Account Level",
  storage_03: "EBS Snapshot Publicly Shared",
  storage_04: "EBS Snapshot Not Encrypted",
  storage_05: "Unattached EBS Volume Older Than 30 Days",
  storage_06: "EBS Snapshot Shared with Unapproved Account",
  storage_07: "EBS Snapshot Lifecycle Manager Not Configured",
  storage_08: "Production EBS Using Deprecated Magnetic Type",
  storage_09: "Sensitive EBS Volume Not Using Customer KMS",
  storage_10: "EFS Encryption at Rest Not Enabled",
  storage_11: "EFS Encryption in Transit Not Enforced",
  storage_12: "EFS Backup Not Enabled",
  storage_13: "EFS Publicly Accessible via Resource Policy",
  storage_14: "EFS Access Points Not Enforcing User Identity",
  storage_15: "Sensitive EFS Not Using Customer KMS Key",
  storage_16: "EFS Mount Targets Not in Private Subnets",
  storage_17: "EFS Lifecycle Management Not Configured",
  storage_18: "EFS Missing Owner/Classification Tags",
  storage_19: "Critical EFS Has No Replication Configured",
  storage_20: "EFS Throughput Mode Not Optimised for Production",

  // ── CloudTrail (logging_monitoring) ───────────────────────
  cloudtrail_01: "CloudTrail Trail Not Actively Logging",
  cloudtrail_02: "No Multi-Region CloudTrail Trail Configured",
  cloudtrail_03: "CloudTrail Log File Validation Disabled",
  cloudtrail_04: "CloudTrail S3 Log Bucket Publicly Accessible",
  cloudtrail_05: "CloudTrail Not Integrated with CloudWatch Logs",
  cloudtrail_06: "CloudTrail Logs Not Encrypted with KMS",
  cloudtrail_07: "CloudTrail Has No SNS Notification",
  cloudtrail_08: "CloudTrail Not Logging Management Events",
  cloudtrail_09: "CloudTrail Logging Write Events Only",
  cloudtrail_10: "CloudTrail Not Logging S3 Data Events",
  cloudtrail_11: "CloudTrail Not Logging Lambda Data Events",
  cloudtrail_12: "CloudTrail Insights Not Enabled",
  cloudtrail_13: "Multi-Region Trail Excludes Global Service Events",
  cloudtrail_14: "CloudTrail Log Retention < 365 Days",
  cloudtrail_15: "CloudTrail S3 Bucket MFA Delete Disabled",

  // ── CloudWatch (logging_monitoring) ───────────────────────
  cloudwatch_01: "No CloudWatch Alarm for Root Account Usage",
  cloudwatch_02: "No CloudWatch Alarm for Unauthorized API Calls",
  cloudwatch_03: "No CloudWatch Alarm for Console Login Without MFA",
  cloudwatch_04: "No CloudWatch Alarm for IAM Policy Changes",
  cloudwatch_05: "No CloudWatch Alarm for CloudTrail Changes",
  cloudwatch_06: "No CloudWatch Alarm for S3 Bucket Policy Changes",
  cloudwatch_07: "No CloudWatch Alarm for VPC Changes",
  cloudwatch_08: "No CloudWatch Alarm for Security Group Changes",
  cloudwatch_09: "No CloudWatch Alarm for NACL Changes",
  cloudwatch_10: "No CloudWatch Alarm for Internet Gateway Changes",
  cloudwatch_11: "CloudWatch Log Group Has No Retention Policy",
  cloudwatch_12: "CloudWatch Log Group Not Encrypted with KMS",
  cloudwatch_13: "CloudWatch Alarm Has No SNS Action",
  cloudwatch_14: "CloudWatch Alarm in INSUFFICIENT_DATA State",
  cloudwatch_15: "No CloudWatch Alarm for Failed Console Sign-In",
  cloudwatch_16: "No CloudWatch Alarm for CMK Deletion/Disable",
  cloudwatch_17: "No CloudWatch Alarm for AWS Config Changes",
  cloudwatch_18: "No CloudWatch Alarm for AWS Organizations Changes",
  cloudwatch_19: "CloudWatch Log Group Retention < 90 Days",
  cloudwatch_20: "No CloudWatch Alarm for Route Table Changes",

  // ── AWS Config (logging_monitoring) ───────────────────────
  config_01: "AWS Config Recorder Not Enabled",
  config_02: "AWS Config Recorder Not Active",
  config_03: "AWS Config Delivery Channel Not Configured",
  config_04: "Config S3 Delivery Bucket Publicly Accessible",
  config_05: "No AWS Config Rules Deployed",
  config_06: "Config No SNS Compliance Notification",
  config_07: "Config Recorder Excludes Global IAM Resources",
  config_08: "Config Multi-Account Aggregator Not Configured",
  config_09: "No Config Conformance Packs Deployed",
  config_10: "Non-Compliant Config Rules Have No Remediation",
  config_11: "Config Snapshot Delivery Not Set to Daily",
  config_12: "AWS Config Rules in ERROR State",

  // ── GuardDuty / Security Hub / Inspector (detection) ──────
  awssec_01: "GuardDuty Detector Not Enabled",
  awssec_02: "No GuardDuty Detector Found",
  awssec_03: "GuardDuty S3 Protection Disabled",
  awssec_04: "GuardDuty Malware Protection for EC2 Disabled",
  awssec_05: "GuardDuty Filter Suppresses HIGH/CRITICAL Findings",
  awssec_06: "GuardDuty Finding Frequency Set to 24 Hours",
  awssec_07: "GuardDuty No SNS Notification for HIGH Findings",
  awssec_08: "AWS Security Hub Not Enabled",
  awssec_09: "Security Hub CIS AWS Foundations Not Enabled",
  awssec_10: "Security Hub FSBP Standard Not Enabled",
  awssec_11: "Security Hub CRITICAL Finding Suppressed Without Note",
  awssec_12: "Security Hub No Delegated Admin Configured",
  awssec_13: "Security Hub No SNS for CRITICAL Findings",
  awssec_14: "AWS Inspector EC2 Scanning Disabled",
  awssec_15: "AWS Inspector ECR Container Scanning Disabled",
  awssec_16: "AWS Inspector Lambda Scanning Disabled",
  awssec_17: "Inspector CRITICAL CVE Open More Than 30 Days",
  awssec_18: "Inspector HIGH CVE Open More Than 90 Days",
  awssec_19: "Inspector Not Integrated with Security Hub",
  awssec_20: "Inspector Suppression Filter Hides CRITICAL Findings",

  // ── Cross-resource ─────────────────────────────────────────
  CROSS_01: "Capital One Attack Pattern",
};

export function getCheckName(checkId: string): string {
  return CHECK_NAMES[checkId] ?? checkId;
}

export default CHECK_NAMES;
