/**
 * Human-readable names for each check ID.
 * Covers both the new service-based policy structure
 * (iam_XX, ec2_XX, s3_XX, …) and the legacy CHECK_XX IDs.
 * Used across violations, policies, remediation, and
 * policy pages.
 */
const CHECK_NAMES: Record<string, string> = {
  // ── IAM (identity) ─────────────────────────────────────────
  iam_root_mfa: "Root Account MFA Not Enabled",
  iam_pwd_min_length: "Password Policy Minimum Length < 14",
  iam_pwd_uppercase: "Password Policy: No Uppercase Required",
  iam_pwd_lowercase: "Password Policy: No Lowercase Required",
  iam_pwd_numbers: "Password Policy: No Numbers Required",
  iam_pwd_symbols: "Password Policy: No Symbols Required",
  iam_pwd_reuse: "Password Policy: Insufficient Reuse Prevention",
  iam_pwd_max_age: "Password Policy: Max Age Exceeds 90 Days",
  iam_user_mfa: "IAM User MFA Not Enabled",
  iam_root_access_keys: "Root Account Has Active Access Keys",
  iam_no_inline_policies: "IAM User Has Inline Policies",
  iam_no_admin_access: "IAM User Has AdministratorAccess",
  iam_key_rotation: "Access Key Not Rotated Within 90 Days",
  iam_inactive_user: "Inactive IAM User With Active Credentials",
  iam_access_analyzer: "IAM Access Analyzer Not Enabled",
  iam_no_wildcard_policy: "IAM Policy Allows Action:* on Resource:*",
  iam_unused_keys: "Unused Access Key Active > 90 Days",
  iam_role_trust_wildcard: "IAM Role Trust Policy Allows All Principals",
  iam_dual_access: "IAM User Has Both Console and API Access",
  iam_support_role: "No IAM Support Role Found",

  // ── Cognito (identity) ─────────────────────────────────────
  cognito_mfa_required: "Cognito User Pool MFA Disabled",
  cognito_pwd_min_length: "Cognito Password Too Short (< 8)",
  cognito_pwd_uppercase: "Cognito: No Uppercase Required",
  cognito_pwd_lowercase: "Cognito: No Lowercase Required",
  cognito_pwd_numbers: "Cognito: No Numbers Required",
  cognito_pwd_symbols: "Cognito: No Symbols Required",
  cognito_advanced_security: "Cognito Advanced Security Not Enforced",
  cognito_temp_pwd_validity: "Cognito Temp Password Validity > 7 Days",
  cognito_verification_required: "Cognito No Auto-Verified Attributes",
  cognito_device_tracking: "Cognito No New Device Challenge",
  cognito_access_token_validity: "Cognito Access Token Valid > 60 Min",
  cognito_refresh_token_validity: "Cognito Refresh Token Valid > 30 Days",
  cognito_no_unauth_identities: "Cognito Identity Pool Allows Unauthenticated",
  cognito_no_user_pwd_auth: "Cognito App Client Uses Plain Password Auth",
  cognito_app_client_secret: "Cognito Server Client Missing Secret",
  cognito_deletion_protection: "Cognito User Pool Deletion Protection Off",
  cognito_ses_sender: "Cognito Using Default Email Sender",

  // ── EC2 (compute) ──────────────────────────────────────────
  ec2_imdsv2: "EC2 IMDSv2 Not Enforced",
  ec2_no_public_ip: "Production EC2 Has Public IP",
  ec2_no_default_vpc: "EC2 Running in Default VPC",
  ec2_detailed_monitoring: "EC2 Detailed Monitoring Disabled",
  ec2_no_open_ssh: "Security Group Allows SSH from 0.0.0.0/0",
  ec2_no_open_rdp: "Security Group Allows RDP from 0.0.0.0/0",
  ec2_no_all_inbound: "Security Group Allows All Inbound Traffic",
  ec2_root_ebs_encrypted: "EC2 Root EBS Volume Not Encrypted",
  ec2_no_admin_role: "EC2 Instance Has Admin IAM Role",
  ec2_snapshot_private: "EBS Snapshot Publicly Accessible",
  ec2_termination_protection: "Production EC2 Termination Protection Off",
  ec2_stopped_cleanup: "EC2 Instance Stopped > 90 Days",
  ec2_no_ipv6_all_ports: "Security Group Allows All IPv6 Inbound",
  ec2_instance_profile: "EC2 Instance Has No IAM Instance Profile",
  ec2_no_open_443_internal: "Internal Security Group Allows HTTPS Public",
  ec2_no_unrestricted_outbound: "Production Security Group Allows All Outbound",
  ec2_no_key_pairs_prod: "Production EC2 Uses Key Pair Instead of SSM",
  ec2_no_deprecated_types: "EC2 Using Deprecated Instance Type",
  ec2_no_unused_eips: "Unused Elastic IP Not Released",
  ec2_ami_private: "Account-Owned AMI Publicly Shared",

  // ── Serverless / Containers (compute) ─────────────────────
  serverless_lambda_xray: "Lambda X-Ray Tracing Not Enabled",
  serverless_lambda_kms_env: "Lambda Env Variables Not KMS Encrypted",
  serverless_lambda_runtime: "Lambda Using Deprecated Runtime",
  serverless_lambda_no_public_invoke:
    "Lambda Resource Policy Allows Public Invocation",
  serverless_lambda_no_admin_role:
    "Lambda Execution Role Has AdministratorAccess",
  serverless_ecs_no_privileged: "ECS Container Running in Privileged Mode",
  serverless_ecs_readonly_root: "ECS Container Root Filesystem Not Read-Only",
  serverless_ecs_cloudwatch_logs: "ECS Container Not Using CloudWatch Logs",
  serverless_ecs_no_host_network: "ECS Task Using Host Network Mode",
  serverless_ecs_container_insights: "ECS Cluster Container Insights Disabled",
  serverless_eks_private_endpoint: "EKS API Endpoint Publicly Accessible",
  serverless_eks_secrets_encryption: "EKS Secrets Encryption Not Enabled",
  serverless_eks_audit_logs: "EKS Audit Logs Not Enabled",
  serverless_eks_private_subnets: "EKS Node Group Not in Private Subnet",
  serverless_eks_version_current: "EKS Using End-of-Life Kubernetes Version",
  serverless_ecr_image_scanning: "ECR Image Scanning Disabled",
  serverless_ecr_private: "ECR Repository Publicly Accessible",
  serverless_ecr_tag_immutability: "ECR Image Tag Immutability Disabled",
  serverless_ecr_lifecycle_policy: "ECR No Lifecycle Policy Configured",
  serverless_ecr_kms_encryption: "ECR Repository Not Encrypted with KMS",

  // ── VPC (network) ──────────────────────────────────────────
  vpc_flow_logs: "VPC Flow Logs Not Enabled",
  vpc_default_no_resources: "Default VPC Has Resources Attached",
  vpc_default_sg_no_inbound: "Default Security Group Allows Inbound",
  vpc_default_sg_no_outbound: "Default Security Group Allows Outbound",
  vpc_nacl_no_all_inbound: "NACL Allows All Inbound from 0.0.0.0/0",
  vpc_dns_resolution: "VPC DNS Resolution Disabled",
  vpc_dns_hostnames: "VPC DNS Hostnames Disabled",
  vpc_private_no_public_ip: "Private Subnet Auto-Assigns Public IPs",
  vpc_private_no_igw_route: "Private Route Table Routes to Internet Gateway",
  vpc_multi_az: "Production VPC Spans Only 1 AZ",
  vpc_sg_no_all_ports: "Security Group Allows All Ports from Internet",
  vpc_peering_internal_cidr: "VPC Peering Connection Uses Unrestricted CIDR",
  vpc_endpoints_s3_dynamodb: "Production VPC Has No S3 VPC Endpoint",
  vpc_cidr_not_slash8: "VPC CIDR Block Too Broad (/8)",
  vpc_nacl_no_admin_ports: "NACL Allows Admin Ports from Internet",
  vpc_tgw_restrict_propagation: "Transit Gateway Default Route Propagation On",
  vpc_private_nat_gateway: "Production VPC Has No NAT Gateway",
  vpc_sg_no_db_ports_open: "Security Group Allows Database Ports from Internet",
  vpc_no_igw_sensitive: "Restricted VPC Has Internet Gateway",
  vpc_flow_logs_reject: "VPC Flow Logs Capture ACCEPT Traffic Only",

  // ── WAF (network) ──────────────────────────────────────────
  waf_cloudfront_association: "WAF Not Associated with CloudFront",
  waf_alb_association: "WAF Not Associated with ALB",
  waf_managed_rules: "AWS Managed WAF Rules Not Enabled",
  waf_rate_based_rules: "WAF Rate-Based Rules Not Configured",
  waf_sqli_protection: "WAF SQL Injection Protection Disabled",
  waf_xss_protection: "WAF XSS Protection Disabled",
  waf_logging: "WAF Logging Not Enabled",
  waf_ip_reputation: "WAF IP Reputation Rules Not Enabled",
  waf_bot_control: "WAF Bot Control Not Enabled",
  waf_no_count_critical: "WAF Critical Rules in COUNT-Only Mode",
  waf_shield_advanced: "AWS Shield Advanced Not Enabled",
  waf_default_block_apis: "WAF API Default Action Not BLOCK",
  waf_known_bad_inputs: "WAF Known Bad Inputs Rules Not Enabled",
  waf_log_redaction: "WAF Log Redaction Hiding Critical Fields",

  // ── API Gateway / Load Balancer (network) ─────────────────
  apigw_access_logging: "API Gateway Access Logging Not Enabled",
  apigw_execution_logging: "API Gateway Execution Logging Not Enabled",
  apigw_tls_12: "API Gateway TLS 1.2 Not Enforced",
  apigw_waf_webacl: "API Gateway WAF WebACL Not Associated",
  apigw_throttling: "API Gateway Throttling Not Configured",
  apigw_vpc_endpoint: "Private API Not Using VPC Endpoint",
  apigw_cors_wildcard: "API Gateway CORS Allows All Origins",
  apigw_api_keys_required: "API Gateway Keys Not Required for Usage Plans",
  apigw_request_validation: "API Gateway Request Validation Disabled",
  apigw_client_certificate: "API Gateway Backend Certificate Missing",
  apigw_lb_https_listener: "Load Balancer Has No HTTPS Listener",
  apigw_lb_tls_12: "Load Balancer TLS Policy Below TLS 1.2",
  apigw_lb_access_logging: "Load Balancer Access Logging Disabled",
  apigw_lb_deletion_protection:
    "Production Load Balancer Deletion Protection Off",
  apigw_lb_http_redirect_https: "Load Balancer HTTP Not Redirecting to HTTPS",
  apigw_lb_internal_not_public: "Internal Load Balancer Is Internet-Facing",
  apigw_lb_waf_webacl: "Production ALB Not Associated with WAF",
  apigw_lb_cert_not_expired: "Load Balancer TLS Certificate Expired",
  apigw_lb_drop_invalid_headers: "Load Balancer Drop Invalid Headers Disabled",
  apigw_lb_multi_az: "Load Balancer Deployed Across Only 1 AZ",

  // ── S3 (data_protection) ───────────────────────────────────
  s3_block_public_acls: "S3 BlockPublicAcls Not Enabled",
  s3_ignore_public_acls: "S3 IgnorePublicAcls Not Enabled",
  s3_block_public_policy: "S3 BlockPublicPolicy Not Enabled",
  s3_restrict_public_buckets: "S3 RestrictPublicBuckets Not Enabled",
  s3_encryption: "S3 Server-Side Encryption Not Enabled",
  s3_versioning: "Sensitive S3 Bucket Versioning Disabled",
  s3_mfa_delete: "Sensitive S3 Bucket MFA Delete Disabled",
  s3_access_logging: "Production S3 Bucket Access Logging Disabled",
  s3_deny_http: "S3 Bucket Policy Allows Unencrypted HTTP",
  s3_no_public_read_acl: "S3 ACL Grants Public Read Access",
  s3_no_public_write_acl: "S3 ACL Grants Public Write Access",
  s3_lifecycle_policy: "Production S3 Bucket Has No Lifecycle Policy",
  s3_object_lock: "Compliance S3 Bucket Object Lock Disabled",
  s3_cors_wildcard: "S3 CORS Configuration Allows All Origins",
  s3_kms_encryption: "Sensitive S3 Bucket Not Using KMS Encryption",
  s3_no_public_principal: "S3 Policy Allows Principal:* Without Conditions",
  s3_replication: "High-Criticality S3 Bucket Has No Replication",
  s3_event_notifications: "Security-Monitored S3 Bucket No Event Notifications",
  s3_cross_account_org_id: "S3 Cross-Account Access Missing Org ID Condition",
  s3_intelligent_tiering: "Large S3 Bucket No Intelligent-Tiering",

  // ── KMS (data_protection) ──────────────────────────────────
  kms_key_rotation: "KMS Customer-Managed Key Rotation Not Enabled",
  kms_no_public_principal: "KMS Key Policy Allows Principal:*",
  kms_pending_deletion_approval:
    "KMS Key Pending Deletion Without Approval Tag",
  kms_separate_admin_users: "KMS Key Policy Mixes Admin and User Roles",
  kms_key_description: "KMS Key Has No Description",
  kms_multi_region_required: "KMS Multi-Region Key Used Without Justification",
  kms_no_unknown_cross_account: "KMS Key Policy Allows Unknown Cross-Account",
  kms_owner_purpose_tags: "KMS Key Missing Owner/Purpose Tags",
  kms_disabled_keys_cleanup: "Disabled KMS Key Not Scheduled for Deletion",
  kms_no_root_wildcard: "KMS Key Policy Grants Root Wildcard Actions",
  kms_no_aws_alias_prefix: "KMS Key Alias Uses Reserved aws/ Prefix",
  kms_s3_rotation: "KMS Key for S3 Rotation Not Enabled",
  kms_deletion_alarm: "No CloudWatch Alarm for KMS Key Deletion",
  kms_external_material_approval: "KMS Key Material Origin Is EXTERNAL",
  kms_decrypt_grant_approved:
    "KMS Key Grant Allows Decrypt to Unapproved Service",

  // ── Secrets Manager (data_protection) ─────────────────────
  secretsmanager_auto_rotation: "Secrets Manager Auto-Rotation Not Enabled",
  secretsmanager_rotation_interval: "Secret Rotation Interval Exceeds 90 Days",
  secretsmanager_no_public_access:
    "Secret Resource Policy Allows Public Access",
  secretsmanager_kms_encryption: "Secret Not Encrypted with Customer KMS Key",
  secretsmanager_unused_cleanup: "Secret Unused for More Than 90 Days",
  secretsmanager_cross_account_org:
    "Secret Has Cross-Account Access Without Condition",
  secretsmanager_deletion_approval:
    "Secret Scheduled for Deletion Without Approval",
  secretsmanager_owner_purpose_tags: "Secret Missing Owner/Purpose Tags",
  secretsmanager_name_not_revealing: "Secret Name Reveals Its Type or Purpose",
  secretsmanager_rotation_validated: "Secret Rotation Function Is Orphaned",
  secretsmanager_description_required: "Secret Has No Description",
  secretsmanager_multi_region:
    "Critical Secret Has No Multi-Region Replication",
  secretsmanager_no_wildcard_principal: "Secret Policy Has Wildcard Principal",

  // ── Database — RDS / DynamoDB / Aurora (data_protection) ──
  db_rds_no_public_access: "RDS Instance Publicly Accessible",
  db_rds_encryption: "RDS Storage Not Encrypted",
  db_rds_backup_retention: "RDS Backup Retention Period < 7 Days",
  db_rds_multi_az: "Production RDS Instance Not Multi-AZ",
  db_rds_deletion_protection: "Production RDS Deletion Protection Off",
  db_rds_iam_auth: "RDS IAM Database Authentication Not Enabled",
  db_rds_snapshot_private: "RDS Snapshot Publicly Accessible",
  db_rds_log_exports: "RDS CloudWatch Log Exports Not Enabled",
  db_rds_auto_minor_upgrade: "RDS Auto Minor Version Upgrade Disabled",
  db_rds_no_default_port: "RDS Using Default Database Port",
  db_dynamodb_kms_encryption: "DynamoDB Encryption Not Using KMS",
  db_dynamodb_pitr: "DynamoDB Point-in-Time Recovery Not Enabled",
  db_dynamodb_deletion_protection:
    "Production DynamoDB Deletion Protection Off",
  db_dynamodb_no_public_policy: "DynamoDB Resource Policy Allows Public Access",
  db_dynamodb_auto_scaling: "Production DynamoDB Auto-Scaling Not Configured",
  db_aurora_no_public_access: "Aurora Cluster Publicly Accessible",
  db_aurora_encryption: "Aurora Storage Not Encrypted",
  db_aurora_deletion_protection: "Production Aurora Deletion Protection Off",
  db_aurora_backtrack: "Aurora Backtrack Not Enabled for Critical Clusters",
  db_aurora_iam_auth: "Aurora IAM Authentication Not Enabled",

  // ── Storage — EBS / EFS (data_protection) ─────────────────
  storage_ebs_encryption: "EBS Volume Not Encrypted",
  storage_ebs_default_encryption:
    "EBS Default Encryption Not Enabled at Account Level",
  storage_ebs_snapshot_private: "EBS Snapshot Publicly Shared",
  storage_ebs_snapshot_encrypted: "EBS Snapshot Not Encrypted",
  storage_ebs_unattached_review: "Unattached EBS Volume Older Than 30 Days",
  storage_ebs_snapshot_approved_accts:
    "EBS Snapshot Shared with Unapproved Account",
  storage_ebs_snapshot_lifecycle:
    "EBS Snapshot Lifecycle Manager Not Configured",
  storage_ebs_no_magnetic: "Production EBS Using Deprecated Magnetic Type",
  storage_ebs_kms_encryption: "Sensitive EBS Volume Not Using Customer KMS",
  storage_efs_encryption_rest: "EFS Encryption at Rest Not Enabled",
  storage_efs_encryption_transit: "EFS Encryption in Transit Not Enforced",
  storage_efs_backup: "EFS Backup Not Enabled",
  storage_efs_no_public_policy: "EFS Publicly Accessible via Resource Policy",
  storage_efs_access_point_enforcement:
    "EFS Access Points Not Enforcing User Identity",
  storage_efs_kms_encryption: "Sensitive EFS Not Using Customer KMS Key",
  storage_efs_private_subnets: "EFS Mount Targets Not in Private Subnets",
  storage_efs_lifecycle: "EFS Lifecycle Management Not Configured",
  storage_efs_tags: "EFS Missing Owner/Classification Tags",
  storage_efs_replication: "Critical EFS Has No Replication Configured",
  storage_efs_throughput_mode:
    "EFS Throughput Mode Not Optimised for Production",

  // ── CloudTrail (logging_monitoring) ───────────────────────
  cloudtrail_enabled: "CloudTrail Trail Not Actively Logging",
  cloudtrail_multi_region: "No Multi-Region CloudTrail Trail Configured",
  cloudtrail_log_validation: "CloudTrail Log File Validation Disabled",
  cloudtrail_s3_private: "CloudTrail S3 Log Bucket Publicly Accessible",
  cloudtrail_cloudwatch_logs: "CloudTrail Not Integrated with CloudWatch Logs",
  cloudtrail_kms_encryption: "CloudTrail Logs Not Encrypted with KMS",
  cloudtrail_sns_notification: "CloudTrail Has No SNS Notification",
  cloudtrail_mgmt_events: "CloudTrail Not Logging Management Events",
  cloudtrail_read_write_events: "CloudTrail Logging Write Events Only",
  cloudtrail_s3_data_events: "CloudTrail Not Logging S3 Data Events",
  cloudtrail_lambda_data_events: "CloudTrail Not Logging Lambda Data Events",
  cloudtrail_insights: "CloudTrail Insights Not Enabled",
  cloudtrail_global_events: "Multi-Region Trail Excludes Global Service Events",
  cloudtrail_retention_365: "CloudTrail Log Retention < 365 Days",
  cloudtrail_s3_mfa_delete: "CloudTrail S3 Bucket MFA Delete Disabled",

  // ── CloudWatch (logging_monitoring) ───────────────────────
  cloudwatch_root_usage_alarm: "No CloudWatch Alarm for Root Account Usage",
  cloudwatch_unauthorized_api_alarm:
    "No CloudWatch Alarm for Unauthorized API Calls",
  cloudwatch_no_mfa_login_alarm:
    "No CloudWatch Alarm for Console Login Without MFA",
  cloudwatch_iam_policy_alarm: "No CloudWatch Alarm for IAM Policy Changes",
  cloudwatch_cloudtrail_alarm: "No CloudWatch Alarm for CloudTrail Changes",
  cloudwatch_s3_policy_alarm:
    "No CloudWatch Alarm for S3 Bucket Policy Changes",
  cloudwatch_vpc_changes_alarm: "No CloudWatch Alarm for VPC Changes",
  cloudwatch_sg_changes_alarm: "No CloudWatch Alarm for Security Group Changes",
  cloudwatch_nacl_changes_alarm: "No CloudWatch Alarm for NACL Changes",
  cloudwatch_igw_changes_alarm:
    "No CloudWatch Alarm for Internet Gateway Changes",
  cloudwatch_log_retention: "CloudWatch Log Group Has No Retention Policy",
  cloudwatch_log_kms_encryption: "CloudWatch Log Group Not Encrypted with KMS",
  cloudwatch_alarm_sns_action: "CloudWatch Alarm Has No SNS Action",
  cloudwatch_no_insufficient_data:
    "CloudWatch Alarm in INSUFFICIENT_DATA State",
  cloudwatch_failed_login_alarm:
    "No CloudWatch Alarm for Failed Console Sign-In",
  cloudwatch_cmk_deletion_alarm: "No CloudWatch Alarm for CMK Deletion/Disable",
  cloudwatch_config_changes_alarm: "No CloudWatch Alarm for AWS Config Changes",
  cloudwatch_org_changes_alarm:
    "No CloudWatch Alarm for AWS Organizations Changes",
  cloudwatch_log_retention_90d: "CloudWatch Log Group Retention < 90 Days",
  cloudwatch_route_table_alarm: "No CloudWatch Alarm for Route Table Changes",

  // ── AWS Config (logging_monitoring) ───────────────────────
  config_recorder_enabled: "AWS Config Recorder Not Enabled",
  config_recorder_active: "AWS Config Recorder Not Active",
  config_delivery_channel: "AWS Config Delivery Channel Not Configured",
  config_s3_private: "Config S3 Delivery Bucket Publicly Accessible",
  config_rules_deployed: "No AWS Config Rules Deployed",
  config_sns_notification: "Config No SNS Compliance Notification",
  config_global_iam_resources: "Config Recorder Excludes Global IAM Resources",
  config_multi_account_aggregator:
    "Config Multi-Account Aggregator Not Configured",
  config_conformance_packs: "No Config Conformance Packs Deployed",
  config_remediation_actions: "Non-Compliant Config Rules Have No Remediation",
  config_daily_snapshots: "Config Snapshot Delivery Not Set to Daily",
  config_no_error_rules: "AWS Config Rules in ERROR State",

  // ── GuardDuty / Security Hub / Inspector (detection) ──────
  awssec_guardduty_enabled: "GuardDuty Detector Not Enabled",
  awssec_guardduty_detector: "No GuardDuty Detector Found",
  awssec_guardduty_s3_protection: "GuardDuty S3 Protection Disabled",
  awssec_guardduty_malware_ec2: "GuardDuty Malware Protection for EC2 Disabled",
  awssec_guardduty_no_suppress_crit:
    "GuardDuty Filter Suppresses HIGH/CRITICAL Findings",
  awssec_guardduty_publish_frequency:
    "GuardDuty Finding Frequency Set to 24 Hours",
  awssec_guardduty_sns_high: "GuardDuty No SNS Notification for HIGH Findings",
  awssec_securityhub_enabled: "AWS Security Hub Not Enabled",
  awssec_securityhub_cis_standard:
    "Security Hub CIS AWS Foundations Not Enabled",
  awssec_securityhub_fsbp_standard: "Security Hub FSBP Standard Not Enabled",
  awssec_securityhub_no_suppress_crit:
    "Security Hub CRITICAL Finding Suppressed Without Note",
  awssec_securityhub_delegated_admin:
    "Security Hub No Delegated Admin Configured",
  awssec_securityhub_sns_critical: "Security Hub No SNS for CRITICAL Findings",
  awssec_inspector_ec2_scanning: "AWS Inspector EC2 Scanning Disabled",
  awssec_inspector_ecr_scanning:
    "AWS Inspector ECR Container Scanning Disabled",
  awssec_inspector_lambda_scanning: "AWS Inspector Lambda Scanning Disabled",
  awssec_inspector_critical_cve_30d:
    "Inspector CRITICAL CVE Open More Than 30 Days",
  awssec_inspector_high_cve_90d: "Inspector HIGH CVE Open More Than 90 Days",
  awssec_inspector_securityhub: "Inspector Not Integrated with Security Hub",
  awssec_inspector_no_suppress_crit:
    "Inspector Suppression Filter Hides CRITICAL Findings",

  // ── Cross-resource ─────────────────────────────────────────
  cross_capital_one_pattern: "Capital One Attack Pattern",
};

/**
 * Maps legacy numeric check IDs (from old DynamoDB
 * records) to current descriptive IDs. Order matches
 * the position of each check in its Rego policy file.
 */
const LEGACY_IDS: Record<string, string> = {
  // IAM
  iam_01: "iam_root_mfa",
  iam_02: "iam_pwd_min_length",
  iam_03: "iam_pwd_uppercase",
  iam_04: "iam_pwd_lowercase",
  iam_05: "iam_pwd_numbers",
  iam_06: "iam_pwd_symbols",
  iam_07: "iam_pwd_reuse",
  iam_08: "iam_pwd_max_age",
  iam_09: "iam_user_mfa",
  iam_10: "iam_root_access_keys",
  iam_11: "iam_no_inline_policies",
  iam_12: "iam_no_admin_access",
  iam_13: "iam_key_rotation",
  iam_14: "iam_inactive_user",
  iam_15: "iam_access_analyzer",
  iam_16: "iam_no_wildcard_policy",
  iam_17: "iam_unused_keys",
  iam_18: "iam_role_trust_wildcard",
  iam_19: "iam_dual_access",
  iam_20: "iam_support_role",
  // Cognito
  cognito_01: "cognito_mfa_required",
  cognito_02: "cognito_pwd_min_length",
  cognito_03: "cognito_pwd_uppercase",
  cognito_04: "cognito_pwd_lowercase",
  cognito_05: "cognito_pwd_numbers",
  cognito_06: "cognito_pwd_symbols",
  cognito_07: "cognito_advanced_security",
  cognito_08: "cognito_temp_pwd_validity",
  cognito_09: "cognito_verification_required",
  cognito_10: "cognito_device_tracking",
  cognito_11: "cognito_access_token_validity",
  cognito_12: "cognito_refresh_token_validity",
  cognito_13: "cognito_no_unauth_identities",
  cognito_14: "cognito_no_user_pwd_auth",
  cognito_15: "cognito_app_client_secret",
  cognito_16: "cognito_deletion_protection",
  cognito_17: "cognito_ses_sender",
  // EC2
  ec2_01: "ec2_imdsv2",
  ec2_02: "ec2_no_public_ip",
  ec2_03: "ec2_no_default_vpc",
  ec2_04: "ec2_detailed_monitoring",
  ec2_05: "ec2_no_open_ssh",
  ec2_06: "ec2_no_open_rdp",
  ec2_07: "ec2_no_all_inbound",
  ec2_08: "ec2_root_ebs_encrypted",
  ec2_09: "ec2_no_admin_role",
  ec2_10: "ec2_snapshot_private",
  ec2_11: "ec2_termination_protection",
  ec2_12: "ec2_stopped_cleanup",
  ec2_13: "ec2_no_ipv6_all_ports",
  ec2_14: "ec2_instance_profile",
  ec2_15: "ec2_no_open_443_internal",
  ec2_16: "ec2_no_unrestricted_outbound",
  ec2_17: "ec2_no_key_pairs_prod",
  ec2_18: "ec2_no_deprecated_types",
  ec2_19: "ec2_no_unused_eips",
  ec2_20: "ec2_ami_private",
  // Serverless
  serverless_01: "serverless_lambda_xray",
  serverless_02: "serverless_lambda_kms_env",
  serverless_03: "serverless_lambda_runtime",
  serverless_04: "serverless_lambda_no_public_invoke",
  serverless_05: "serverless_lambda_no_admin_role",
  serverless_06: "serverless_ecs_no_privileged",
  serverless_07: "serverless_ecs_readonly_root",
  serverless_08: "serverless_ecs_cloudwatch_logs",
  serverless_09: "serverless_ecs_no_host_network",
  serverless_10: "serverless_ecs_container_insights",
  serverless_11: "serverless_eks_private_endpoint",
  serverless_12: "serverless_eks_secrets_encryption",
  serverless_13: "serverless_eks_audit_logs",
  serverless_14: "serverless_eks_private_subnets",
  serverless_15: "serverless_eks_version_current",
  serverless_16: "serverless_ecr_image_scanning",
  serverless_17: "serverless_ecr_private",
  serverless_18: "serverless_ecr_tag_immutability",
  serverless_19: "serverless_ecr_lifecycle_policy",
  serverless_20: "serverless_ecr_kms_encryption",
  // S3
  s3_01: "s3_block_public_acls",
  s3_02: "s3_ignore_public_acls",
  s3_03: "s3_block_public_policy",
  s3_04: "s3_restrict_public_buckets",
  s3_05: "s3_encryption",
  s3_06: "s3_versioning",
  s3_07: "s3_mfa_delete",
  s3_08: "s3_access_logging",
  s3_09: "s3_deny_http",
  s3_10: "s3_no_public_read_acl",
  s3_11: "s3_no_public_write_acl",
  s3_12: "s3_lifecycle_policy",
  s3_13: "s3_object_lock",
  s3_14: "s3_cors_wildcard",
  s3_15: "s3_kms_encryption",
  s3_16: "s3_no_public_principal",
  s3_17: "s3_replication",
  s3_18: "s3_event_notifications",
  s3_19: "s3_cross_account_org_id",
  s3_20: "s3_intelligent_tiering",
  // KMS
  kms_01: "kms_key_rotation",
  kms_02: "kms_no_public_principal",
  kms_03: "kms_pending_deletion_approval",
  kms_04: "kms_separate_admin_users",
  kms_05: "kms_key_description",
  kms_06: "kms_multi_region_required",
  kms_07: "kms_no_unknown_cross_account",
  kms_08: "kms_owner_purpose_tags",
  kms_09: "kms_disabled_keys_cleanup",
  kms_10: "kms_no_root_wildcard",
  kms_11: "kms_no_aws_alias_prefix",
  kms_12: "kms_s3_rotation",
  kms_13: "kms_deletion_alarm",
  kms_14: "kms_external_material_approval",
  kms_15: "kms_decrypt_grant_approved",
  // Secrets Manager
  secretsmanager_01: "secretsmanager_auto_rotation",
  secretsmanager_02: "secretsmanager_rotation_interval",
  secretsmanager_03: "secretsmanager_no_public_access",
  secretsmanager_04: "secretsmanager_kms_encryption",
  secretsmanager_05: "secretsmanager_unused_cleanup",
  secretsmanager_06: "secretsmanager_cross_account_org",
  secretsmanager_07: "secretsmanager_deletion_approval",
  secretsmanager_08: "secretsmanager_owner_purpose_tags",
  secretsmanager_09: "secretsmanager_name_not_revealing",
  secretsmanager_10: "secretsmanager_rotation_validated",
  secretsmanager_11: "secretsmanager_description_required",
  secretsmanager_12: "secretsmanager_multi_region",
  secretsmanager_13: "secretsmanager_no_wildcard_principal",
  // Database
  db_01: "db_rds_no_public_access",
  db_02: "db_rds_encryption",
  db_03: "db_rds_backup_retention",
  db_04: "db_rds_multi_az",
  db_05: "db_rds_deletion_protection",
  db_06: "db_rds_iam_auth",
  db_07: "db_rds_snapshot_private",
  db_08: "db_rds_log_exports",
  db_09: "db_rds_auto_minor_upgrade",
  db_10: "db_rds_no_default_port",
  db_11: "db_dynamodb_kms_encryption",
  db_12: "db_dynamodb_pitr",
  db_13: "db_dynamodb_deletion_protection",
  db_14: "db_dynamodb_no_public_policy",
  db_15: "db_dynamodb_auto_scaling",
  db_16: "db_aurora_no_public_access",
  db_17: "db_aurora_encryption",
  db_18: "db_aurora_deletion_protection",
  db_19: "db_aurora_backtrack",
  db_20: "db_aurora_iam_auth",
  // Storage
  storage_01: "storage_ebs_encryption",
  storage_02: "storage_ebs_default_encryption",
  storage_03: "storage_ebs_snapshot_private",
  storage_04: "storage_ebs_snapshot_encrypted",
  storage_05: "storage_ebs_unattached_review",
  storage_06: "storage_ebs_snapshot_approved_accts",
  storage_07: "storage_ebs_snapshot_lifecycle",
  storage_08: "storage_ebs_no_magnetic",
  storage_09: "storage_ebs_kms_encryption",
  storage_10: "storage_efs_encryption_rest",
  storage_11: "storage_efs_encryption_transit",
  storage_12: "storage_efs_backup",
  storage_13: "storage_efs_no_public_policy",
  storage_14: "storage_efs_access_point_enforcement",
  storage_15: "storage_efs_kms_encryption",
  storage_16: "storage_efs_private_subnets",
  storage_17: "storage_efs_lifecycle",
  storage_18: "storage_efs_tags",
  storage_19: "storage_efs_replication",
  storage_20: "storage_efs_throughput_mode",
  // VPC
  vpc_01: "vpc_flow_logs",
  vpc_02: "vpc_default_no_resources",
  vpc_03: "vpc_default_sg_no_inbound",
  vpc_04: "vpc_default_sg_no_outbound",
  vpc_05: "vpc_nacl_no_all_inbound",
  vpc_06: "vpc_dns_resolution",
  vpc_07: "vpc_dns_hostnames",
  vpc_08: "vpc_private_no_public_ip",
  vpc_09: "vpc_private_no_igw_route",
  vpc_10: "vpc_multi_az",
  vpc_11: "vpc_sg_no_all_ports",
  vpc_12: "vpc_peering_internal_cidr",
  vpc_13: "vpc_endpoints_s3_dynamodb",
  vpc_14: "vpc_cidr_not_slash8",
  vpc_15: "vpc_nacl_no_admin_ports",
  vpc_16: "vpc_tgw_restrict_propagation",
  vpc_17: "vpc_private_nat_gateway",
  vpc_18: "vpc_sg_no_db_ports_open",
  vpc_19: "vpc_no_igw_sensitive",
  vpc_20: "vpc_flow_logs_reject",
  // WAF
  waf_01: "waf_cloudfront_association",
  waf_02: "waf_alb_association",
  waf_03: "waf_managed_rules",
  waf_04: "waf_rate_based_rules",
  waf_05: "waf_sqli_protection",
  waf_06: "waf_xss_protection",
  waf_07: "waf_logging",
  waf_08: "waf_ip_reputation",
  waf_09: "waf_bot_control",
  waf_10: "waf_no_count_critical",
  waf_11: "waf_shield_advanced",
  waf_12: "waf_default_block_apis",
  waf_13: "waf_known_bad_inputs",
  waf_14: "waf_log_redaction",
  // API Gateway
  apigw_01: "apigw_access_logging",
  apigw_02: "apigw_execution_logging",
  apigw_03: "apigw_tls_12",
  apigw_04: "apigw_waf_webacl",
  apigw_05: "apigw_throttling",
  apigw_06: "apigw_vpc_endpoint",
  apigw_07: "apigw_cors_wildcard",
  apigw_08: "apigw_api_keys_required",
  apigw_09: "apigw_request_validation",
  apigw_10: "apigw_client_certificate",
  apigw_11: "apigw_lb_https_listener",
  apigw_12: "apigw_lb_tls_12",
  apigw_13: "apigw_lb_access_logging",
  apigw_14: "apigw_lb_deletion_protection",
  apigw_15: "apigw_lb_http_redirect_https",
  apigw_16: "apigw_lb_internal_not_public",
  apigw_17: "apigw_lb_waf_webacl",
  apigw_18: "apigw_lb_cert_not_expired",
  apigw_19: "apigw_lb_drop_invalid_headers",
  apigw_20: "apigw_lb_multi_az",
  // CloudTrail
  cloudtrail_01: "cloudtrail_enabled",
  cloudtrail_02: "cloudtrail_multi_region",
  cloudtrail_03: "cloudtrail_log_validation",
  cloudtrail_04: "cloudtrail_s3_private",
  cloudtrail_05: "cloudtrail_cloudwatch_logs",
  cloudtrail_06: "cloudtrail_kms_encryption",
  cloudtrail_07: "cloudtrail_sns_notification",
  cloudtrail_08: "cloudtrail_mgmt_events",
  cloudtrail_09: "cloudtrail_read_write_events",
  cloudtrail_10: "cloudtrail_s3_data_events",
  cloudtrail_11: "cloudtrail_lambda_data_events",
  cloudtrail_12: "cloudtrail_insights",
  cloudtrail_13: "cloudtrail_global_events",
  cloudtrail_14: "cloudtrail_retention_365",
  cloudtrail_15: "cloudtrail_s3_mfa_delete",
  // CloudWatch
  cloudwatch_01: "cloudwatch_root_usage_alarm",
  cloudwatch_02: "cloudwatch_unauthorized_api_alarm",
  cloudwatch_03: "cloudwatch_no_mfa_login_alarm",
  cloudwatch_04: "cloudwatch_iam_policy_alarm",
  cloudwatch_05: "cloudwatch_cloudtrail_alarm",
  cloudwatch_06: "cloudwatch_s3_policy_alarm",
  cloudwatch_07: "cloudwatch_vpc_changes_alarm",
  cloudwatch_08: "cloudwatch_sg_changes_alarm",
  cloudwatch_09: "cloudwatch_nacl_changes_alarm",
  cloudwatch_10: "cloudwatch_igw_changes_alarm",
  cloudwatch_11: "cloudwatch_log_retention",
  cloudwatch_12: "cloudwatch_log_kms_encryption",
  cloudwatch_13: "cloudwatch_alarm_sns_action",
  cloudwatch_14: "cloudwatch_no_insufficient_data",
  cloudwatch_15: "cloudwatch_failed_login_alarm",
  cloudwatch_16: "cloudwatch_cmk_deletion_alarm",
  cloudwatch_17: "cloudwatch_config_changes_alarm",
  cloudwatch_18: "cloudwatch_org_changes_alarm",
  cloudwatch_19: "cloudwatch_log_retention_90d",
  cloudwatch_20: "cloudwatch_route_table_alarm",
  // Config
  config_01: "config_recorder_enabled",
  config_02: "config_recorder_active",
  config_03: "config_delivery_channel",
  config_04: "config_s3_private",
  config_05: "config_rules_deployed",
  config_06: "config_sns_notification",
  config_07: "config_global_iam_resources",
  config_08: "config_multi_account_aggregator",
  config_09: "config_conformance_packs",
  config_10: "config_remediation_actions",
  config_11: "config_daily_snapshots",
  config_12: "config_no_error_rules",
  // AWS Security (GuardDuty / Security Hub / Inspector)
  awssec_01: "awssec_guardduty_enabled",
  awssec_02: "awssec_guardduty_detector",
  awssec_03: "awssec_guardduty_s3_protection",
  awssec_04: "awssec_guardduty_malware_ec2",
  awssec_05: "awssec_guardduty_no_suppress_crit",
  awssec_06: "awssec_guardduty_publish_frequency",
  awssec_07: "awssec_guardduty_sns_high",
  awssec_08: "awssec_securityhub_enabled",
  awssec_09: "awssec_securityhub_cis_standard",
  awssec_10: "awssec_securityhub_fsbp_standard",
  awssec_11: "awssec_securityhub_no_suppress_crit",
  awssec_12: "awssec_securityhub_delegated_admin",
  awssec_13: "awssec_securityhub_sns_critical",
  awssec_14: "awssec_inspector_ec2_scanning",
  awssec_15: "awssec_inspector_ecr_scanning",
  awssec_16: "awssec_inspector_lambda_scanning",
  awssec_17: "awssec_inspector_critical_cve_30d",
  awssec_18: "awssec_inspector_high_cve_90d",
  awssec_19: "awssec_inspector_securityhub",
  awssec_20: "awssec_inspector_no_suppress_crit",
};

/**
 * Return a human-readable name for a check ID.
 * Resolves legacy numeric IDs (e.g. awssec_09) to their
 * current descriptive names via LEGACY_IDS, then looks up
 * CHECK_NAMES for the display string.
 */
export function getCheckName(checkId: string): string {
  // Direct match
  if (CHECK_NAMES[checkId]) return CHECK_NAMES[checkId];

  // Legacy numeric ID → new descriptive ID → name
  const newId = LEGACY_IDS[checkId];
  if (newId && CHECK_NAMES[newId]) return CHECK_NAMES[newId];

  // Readable fallback: title-case the raw ID
  return checkId
    .replace(/_(\d+)$/, " $1")
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

export default CHECK_NAMES;
