/**
 * Official short names for compliance framework control IDs.
 * Used in the compliance drill-down table Name column.
 */
const CONTROL_NAMES: Record<string, string> = {
  // ── CIS AWS Foundations Benchmark v1.5.0 ───────────────────────
  "1.1": "Security Contact Details",
  "1.4": "No Root Access Keys",
  "1.5": "Root Account MFA",
  "1.9": "IAM Password Reuse Prevention",
  "1.10": "MFA for IAM Console Users",
  "1.12": "Disable Inactive Credentials",
  "1.13": "One Active Access Key Per User",
  "1.14": "Access Key Rotation (90 Days)",
  "1.15": "IAM Permissions via Groups Only",
  "1.16": "IAM Policy Attachment Restrictions",
  "1.20": "IAM Support Role",
  "1.21": "No Initial Setup Access Keys",
  "2.1.1": "S3 Block Public ACLs",
  "2.1.2": "S3 Block Public Policy",
  "2.1.3": "S3 Ignore Public ACLs",
  "2.1.4": "S3 Restrict Public Buckets",
  "2.1.5": "S3 MFA Delete Enabled",
  "2.2.1": "EBS Default Encryption",
  "2.2.2": "EBS Snapshots Not Public",
  "2.2.3": "EBS Volume Encryption",
  "2.3.1": "RDS Encryption at Rest",
  "2.3.2": "RDS Snapshots Not Public",
  "2.3.3": "RDS Instance Not Publicly Accessible",
  "2.3.4": "RDS Deletion Protection",
  "2.3.5": "RDS Aurora Deletion Protection",
  "2.4.1": "Aurora Backtrack Enabled",
  "2.5.1": "ECR Repository Private",
  "2.5.2": "ECR Image Scanning",
  "2.8": "KMS Key Rotation",
  "3.1": "CloudTrail Multi-Region",
  "3.2": "CloudTrail Log Validation",
  "3.3": "CloudTrail S3 Bucket Not Public",
  "3.4": "CloudTrail Log Encryption",
  "3.5": "AWS Config Enabled",
  "3.6": "CloudWatch Unauthorized API Calls",
  "3.7": "CloudWatch Console MFA Sign-in",
  "3.9": "VPC Flow Logs Enabled",
  "3.10": "API Gateway Access Logging",
  "3.11": "CloudTrail S3 Bucket MFA Delete",
  "3.12": "CloudWatch Security Group Changes",
  "4.1": "CloudWatch Root Usage Alarm",
  "4.2": "CloudWatch Unauthorized API Alarm",
  "4.3": "CloudWatch MFA Sign-in Alarm",
  "4.4": "CloudWatch IAM Policy Changes Alarm",
  "4.5": "CloudWatch CloudTrail Changes Alarm",
  "4.6": "CloudWatch S3 Policy Changes Alarm",
  "4.7": "CloudWatch Config Changes Alarm",
  "4.8": "CloudWatch Security Group Alarm",
  "4.9": "CloudWatch Network ACL Alarm",
  "4.10": "CloudWatch Internet Gateway Alarm",
  "4.11": "CloudWatch Route Table Changes Alarm",
  "4.12": "CloudWatch VPC Changes Alarm",
  "4.13": "CloudWatch Organizations Policy Alarm",
  "4.14": "CloudWatch RDS Security Group Alarm",
  "4.15": "GuardDuty Enabled",
  "5.1": "ELB HTTPS Listeners",
  "5.2": "No Admin Ports Open to Public",
  "5.3": "No SSH Open to Internet",
  "5.4": "No RDP Open to Internet",
  "5.5": "Default VPC Security Group Closed",
  "5.6": "EC2 IMDSv2 Enforced",

  // ── NIST 800-53 ────────────────────────────────────────────────
  "AC-2": "Account Management",
  "AC-2(3)": "Account Management — Disable Inactive",
  "AC-3": "Access Enforcement",
  "AC-4": "Information Flow Enforcement",
  "AC-5": "Separation of Duties",
  "AC-6": "Least Privilege",
  "AC-6(5)": "Least Privilege — Privileged Accounts",
  "AC-7": "Unsuccessful Login Attempts",
  "AC-12": "Session Termination",
  "AC-17": "Remote Access",
  "AU-2": "Audit Events",
  "AU-3": "Content of Audit Records",
  "AU-6": "Audit Review",
  "AU-9": "Protection of Audit Information",
  "AU-11": "Audit Record Retention",
  "AU-12": "Audit Record Generation",
  "CA-7": "Continuous Monitoring",
  "CM-3": "Configuration Change Control",
  "CM-6": "Configuration Settings",
  "CM-7": "Least Functionality",
  "CM-8": "System Component Inventory",
  "CP-7": "Alternate Processing Site",
  "CP-9": "System Backup",
  "IA-2": "Identification and Authentication",
  "IA-2(1)": "Multi-Factor Authentication",
  "IA-3": "Device Identification",
  "IA-5": "Authenticator Management",
  "IA-5(1)": "Password Complexity",
  "IR-2": "Incident Response Training",
  "IR-6": "Incident Reporting",
  "MP-6": "Media Sanitization",
  "SC-5": "Denial-of-Service Protection",
  "SC-7": "Boundary Protection",
  "SC-8": "Transmission Confidentiality",
  "SC-12": "Cryptographic Key Management",
  "SC-20": "Secure Name Resolution",
  "SC-28": "Protection of Data at Rest",
  "SC-28(1)": "Data at Rest — Cryptographic Protection",
  "SI-2": "Flaw Remediation",
  "SI-3": "Malicious Code Protection",
  "SI-4": "System Monitoring",
  "SI-7": "Software Integrity",
  "SI-10": "Information Input Validation",
  "SI-12": "Information Output Handling",

  // ── PCI DSS v4.0 ───────────────────────────────────────────────
  "1.3.1": "Restrict Inbound Network Access",
  "1.3.4": "Restrict Outbound Network Access",
  "3.3.1": "Sensitive Data Retention Limits",
  "3.5.1": "Primary Account Number Protection",
  "3.7.1": "Key Management Procedures",
  "3.7.2": "Key Change Procedures",
  "3.7.3": "Key Retirement and Replacement",
  "3.7.4": "Cryptoperiod Enforcement",
  "4.2.1": "Encryption in Transit",
  "5.2.2": "Anti-Malware Solution",
  "6.2.4": "Secure Development Techniques",
  "6.3.2": "Software Inventory",
  "6.3.3": "Security Patches Applied",
  "6.4.1": "Web Application Security",
  "6.4.2": "Application Security Review",
  "6.4.3": "Script Management",
  "7.2.1": "Access Control System",
  "7.2.4": "User Account Reviews",
  "8.2.6": "Inactive User Accounts",
  "8.2.8": "Session Idle Timeout",
  "8.3.1": "Strong Authentication Required",
  "8.3.6": "Password Complexity Requirements",
  "8.3.7": "Password Reuse Prevention",
  "8.3.9": "Password Change Period",
  "8.4.2": "MFA for Non-Console Access",
  "8.4.3": "MFA for All Access",
  "10.1": "Audit Log Implementation",
  "10.2": "Audit Log Capture",
  "10.2.1.1": "Individual User Actions Logged",
  "10.2.1.2": "Root and Admin Actions Logged",
  "10.2.1.3": "Audit Log Access Logged",
  "10.2.1.6": "Diagnostic Functions Logged",
  "10.3": "Audit Log Protection",
  "10.5": "Audit Log Review",
  "10.5.2": "Automated Log Review",
  "10.7": "Security Control Failure Detection",
  "11.5": "Intrusion Detection",
  "12.3.2": "Targeted Risk Analysis",
  "12.3.4": "Hardware Inventory Review",

  // ── HIPAA ──────────────────────────────────────────────────────
  "164.308(a)(7)": "Contingency Plan",
  "164.312(a)(2)(iv)": "Encryption and Decryption",
  "164.312(b)": "Audit Controls",
  "164.312(c)(1)": "Data Integrity",
  "164.312(d)": "Person Authentication",
  "164.312(e)(2)(i)": "Transmission Encryption",

  // ── SOC 2 ──────────────────────────────────────────────────────
  "A1.1": "Capacity Management",
  "A1.2": "Environmental Protections",
  "C1.1": "Confidentiality Protections",
  "CC6.1": "Logical Access Security",
  "CC6.2": "User Authentication",
  "CC6.3": "Authorization",
  "CC6.6": "Network Access Boundaries",
  "CC6.7": "Transmission Protection",
  "CC6.8": "Malware Protection",
  "CC7.1": "System Operations",
  "CC7.2": "Change Detection",
  "CC7.3": "Incident Response",
  "CC7.4": "Incident Resolution",
  "CC8.1": "Change Management",

  // ── OWASP Top 10 (2025) ────────────────────────────────────────
  "A01:2025": "Broken Access Control",
  "A02:2025": "Cryptographic Failures",
  "A03:2025": "Injection",
  "A04:2025": "Insecure Design",
  "A05:2025": "Security Misconfiguration",
  "A06:2025": "Vulnerable and Outdated Components",
  "A07:2025": "Identification and Auth Failures",
  "A08:2025": "Software and Data Integrity Failures",
  "A09:2025": "Security Logging and Monitoring Failures",
  "A10:2025": "Server-Side Request Forgery",
};

export function getControlName(controlId: string): string {
  return CONTROL_NAMES[controlId] ?? controlId;
}
